apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hqrbul9hz-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hqrbul9hz-dotnet-basic-gitops